#!/usr/bin/env bash
# 0-Double the number of webservers.

sudo apt-get -y update
sudo apt-get -y install nginx
configuration="/etc/nginx/sites-available/default"
sudo sh -c "echo 'Hello World!' > /var/www/html/index.nginx-debian.html"
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}' $configuration
sudo sed -i '/^}$/i \ \n\tlocation @404 {return 404 "Ceci n'\''est pas une page\\n";}' $configuration
sudo sed -i 's/=404/@404/g' $configuration
sudo sed -i "0,/location \/ {/s/location \/ {/&\n\t\tadd_header X-Served-By '$HOSTNAME';/" $configuration
sudo service nginx restart
