#!/usr/bin/env bash
# 1-install your load balancer.

sudo apt update
sudo apt install haproxy -y
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver server1 34.229.161.69 check\n\tserver server2 54.237.124.75 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
